import Foundation

/// Shell completion, generated from the command catalog.
///
/// Written by hand, a completion script becomes wrong at the next release and nothing notices:
/// a command added to the catalog would simply never be offered. Generating it from the same
/// data that builds the help and validates the flags means there is one list, not two.
public enum CompletionScript {
    public enum Shell: String, CaseIterable, Sendable {
        case zsh, bash
    }

    /// Flags whose value is a directory: completion offers directories only, because offering
    /// files there is noise the user has to step over every time.
    static let directoryFlags: Set<String> = ["--project", "--scope", "--index-store"]
    /// Flags whose value is a file.
    static let fileFlags: Set<String> = ["--rules", "--spec", "--index-lib"]

    public static func script(for shell: Shell) -> String {
        switch shell {
        case .zsh: return zsh()
        case .bash: return bash()
        }
    }

    // MARK: - zsh

    private static func zsh() -> String {
        let commands = CommandCatalog.commands
            .map { "    '\($0.name):\(escapeForZsh($0.summary))'" }
            .joined(separator: "\n")

        let perCommand = CommandCatalog.commands.map { command -> String in
            let specs = command.flags.map { flag -> String in
                let description = escapeForZsh(flag.summary)
                guard flag.takesValue else { return "        '\(flag.name)[\(description)]' \\" }
                // A flag that takes a value must consume one, or the shell would offer the next
                // flag where an argument belongs.
                let action = valueAction(for: flag.name, shell: .zsh)
                return "        '\(flag.name)[\(description)]:value:\(action)' \\"
            }.joined(separator: "\n")
            return """
                    \(command.name))
                      _arguments \\
            \(specs.isEmpty ? "        '*: :_files'" : specs + "\n            '*: :_files'")
                      ;;
            """
        }.joined(separator: "\n")

        return """
        #compdef sextant
        # Generated by `sextant completion zsh` — do not edit; regenerate after an upgrade.

        _sextant() {
          local -a _sextant_commands
          _sextant_commands=(
        \(commands)
          )

          local context state state_descr line
          typeset -A opt_args
          _arguments -C '1: :->command' '*:: :->argument'

          case $state in
            command)
              _describe -t commands 'sextant command' _sextant_commands
              ;;
            argument)
              case $words[1] in
        \(perCommand)
                *)
                  _files
                  ;;
              esac
              ;;
          esac
        }

        _sextant "$@"
        """
    }

    // MARK: - bash

    private static func bash() -> String {
        let names = CommandCatalog.commands.map { $0.name }.joined(separator: " ")
        let directoryValueFlags = valueFlags(in: directoryFlags).joined(separator: "|")
        let fileValueFlags = valueFlags(in: fileFlags).joined(separator: "|")
        let otherValueFlags = CommandCatalog.commands
            .flatMap { $0.flags }
            .filter { $0.takesValue && !directoryFlags.contains($0.name) && !fileFlags.contains($0.name) }
            .map { $0.name }
            .uniqued()
            .joined(separator: "|")

        let perCommand = CommandCatalog.commands.map { command in
            "    \(command.name)) flags=\"\(command.flags.map { $0.name }.joined(separator: " "))\" ;;"
        }.joined(separator: "\n")

        return """
        # Generated by `sextant completion bash` — do not edit; regenerate after an upgrade.

        _sextant() {
          local cur prev command flags
          cur="${COMP_WORDS[COMP_CWORD]}"
          prev="${COMP_WORDS[COMP_CWORD-1]}"

          if [ "$COMP_CWORD" -eq 1 ]; then
            COMPREPLY=( $(compgen -W "\(names)" -- "$cur") )
            return
          fi

          # A flag that takes a value gets a value, not another flag.
          case "$prev" in
            \(directoryValueFlags))
              COMPREPLY=( $(compgen -d -- "$cur") )
              return
              ;;
            \(fileValueFlags))
              COMPREPLY=( $(compgen -f -- "$cur") )
              return
              ;;
            \(otherValueFlags))
              return
              ;;
          esac

          command="${COMP_WORDS[1]}"
          case "$command" in
        \(perCommand)
            *) flags="" ;;
          esac

          if [[ "$cur" == -* ]]; then
            COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
          else
            COMPREPLY=( $(compgen -f -- "$cur") )
          fi
        }

        complete -F _sextant sextant
        """
    }

    // MARK: - Helpers

    private static func valueFlags(in group: Set<String>) -> [String] {
        CommandCatalog.commands
            .flatMap { $0.flags }
            .filter { $0.takesValue && group.contains($0.name) }
            .map { $0.name }
            .uniqued()
    }

    private static func valueAction(for flag: String, shell: Shell) -> String {
        if directoryFlags.contains(flag) { return "_files -/" }
        if fileFlags.contains(flag) { return "_files" }
        return " "                                   // an opaque value: no suggestion, but one is expected
    }

    /// `_arguments` reads `:` and `[` as syntax, so a summary carrying them would break the spec
    /// it lands in.
    private static func escapeForZsh(_ text: String) -> String {
        text.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: ":", with: "\\:")
            .replacingOccurrences(of: "[", with: "\\[")
            .replacingOccurrences(of: "]", with: "\\]")
            .replacingOccurrences(of: "'", with: "'\\''")
    }
}

private extension Array where Element == String {
    func uniqued() -> [String] {
        var seen = Set<String>()
        return filter { seen.insert($0).inserted }
    }
}
